kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: nginx

spec:
  completions: 2
  parallelism: 1
  template:
    metadata:
      name: demo-job-prod
      labels:
        app: batch-task

    spec:
      containers:
        - name: batch-container
          image: busybox:latest
          command: ["sh", "-c", "echo Hello DOSOTO!!! && sleep 10"]
      restartPolicy: Never
